Repository wecode-bootcamp-korea/24-2nd-FLIP-frontend, pull requests merged in 2021-09, with the labels that each got.

#2 [24기 김세준] MODIFY: theme.js 색상변경
  src/styles/theme.js
Labels: Status: 리뷰 요청

#5 [24기 김세준] Add: 메인페이지 footer 레이아웃 구현 완료
  src/components/Footer/Footer.js
  src/styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#8 [지의선] EDIT: 카드컴포넌트 수정 백엔드와 데이터 붙여보기 완료
  public/data/CardMockData.json
  src/components/Card/Card.js
  src/components/Card/CardList.js
  src/components/Card/Explanation.js
  src/components/Card/StarImg.js
  src/pages/Main/Main.js
Labels: Status: Accepted

#12 [지의선] EDIT: 카드컴포넌트 수정
  src/components/Card/Card.js
  src/components/Card/CardList.js
Labels: Status: Accepted

#10 [24기 김세준] Add: Main 페이지 구현
  package-lock.json
  package.json
  public/data/categoryIcons.json
  src/pages/Main/CategoryList/CategoryList.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#11 [지의선]WIP: 서브카테고리 필터링 구현중 & 동적라우팅 구현 중
  package-lock.json
  package.json
  public/index.html
  src/pages/ProductList/Modal.js
  src/pages/ProductList/ProductCard.js
  src/pages/ProductList/ProductCardList.js
  src/pages/ProductList/ProductExplanation.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductStarImg.js
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#15 [24기 김세준] 메인페이지 에러 해결
  src/components/Card/Card.js
Labels: Status: 리뷰 요청

#14 [24기 김세준] 상품 등록페이지 구현
  package-lock.json
  package.json
  src/Routes.js
  src/pages/AddProduct/AddProduct.js
  src/pages/AddProduct/ImageUpload.js
  src/pages/AddProduct/Postcode.js
  yarn.lock
Labels: Status: 리뷰 요청

#3 [24기 김세준] Add: 네이게이션바 레이아웃 완료
  package-lock.json
  package.json
  public/image/logo.png
  src/components/Nav/Nav.js
Labels: Status: 수정 요청
